### PR TITLE
feat: Added support for mTLS and the ability to disable default endpoint

### LINKED ISSUE #12: feat: Support client auth with truststore
Can you add support for client-authentication with certificates by adding support for truststore: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_domain_name#mutual_tls_authentication

### PR DESCRIPTION
**Pull request by davidkarlsen**
## Description
Adds fixes for review-comments in #18.

## Motivation and Context
Adds mtls support, fixes #12.

## Breaking Changes
No breaking changes.

## How Has This Been Tested?
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects
I have not tested it.

### CODE REVIEW

**Comment by antonbabenko** [comment]
Hi @davidkarlsen !

Please update an example to show a case for mTLS.

**Comment by davidkarlsen** [comment]
@antonbabenko added

**Review by antonbabenko — APPROVED** [review]
It works :)

**Comment by antonbabenko** [comment]
Thanks @davidkarlsen !

[v0.15.0](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/releases/v0.15.0) has been just released.

**Pull request merged**
