### PR TITLE
feat: Add pass-through of ownership_verification_certificate_arn to domain_name

### PR DESCRIPTION
**Pull request by kmannuz**
## Description

Adds the ability to also pass `ownership_verification_certificate_arn` to `domain_name` resource as new variable called `domain_name_ownership_verification_certificate_arn`. I followed existing patterns for defaults and naming conventions.

## Motivation and Context

Users may need to configure `ownership_verification_certificate_arn` as part of `aws_apigatewayv2_domain_name`. See [provider docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_domain_name#ownership_verification_certificate_arn) for use cases 

## Breaking Changes

N/A - defaults to null, which is currently implied

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [X] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [X] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by antonbabenko — COMMENTED** [review]
LGTM, please update the minimum version of AWS provider in `versions.tf` to be `>= 4.0` since this feature was added in 4.0.0.

**Comment by kmannuz** [comment]
> LGTM, please update the minimum version of AWS provider in `versions.tf` to be `>= 4.0` since this feature was added in 4.0.0.

Done!

**Comment by antonbabenko** [comment]
This PR is included in version 1.9.0 :tada:

**Comment by antonbabenko** [comment]
I have made a mistake (#73) by not bumping a major version when merging this PR.

v1.9.0 should not have been created. Please use v2.0.0 which was created in #74.

Sorry for the confusion!

**Pull request merged**
